// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/gophkeeper/gophkeeper/internal/domain/repository (interfaces: DataRepository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_data_repository.go -package=mocks github.com/gophkeeper/gophkeeper/internal/domain/repository DataRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	models "github.com/gophkeeper/gophkeeper/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockDataRepository is a mock of DataRepository interface.
type MockDataRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDataRepositoryMockRecorder
	isgomock struct{}
}

// MockDataRepositoryMockRecorder is the mock recorder for MockDataRepository.
type MockDataRepositoryMockRecorder struct {
	mock *MockDataRepository
}

// NewMockDataRepository creates a new mock instance.
func NewMockDataRepository(ctrl *gomock.Controller) *MockDataRepository {
	mock := &MockDataRepository{ctrl: ctrl}
	mock.recorder = &MockDataRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDataRepository) EXPECT() *MockDataRepositoryMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockDataRepository) Delete(ctx context.Context, userID, dataID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, userID, dataID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockDataRepositoryMockRecorder) Delete(ctx, userID, dataID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDataRepository)(nil).Delete), ctx, userID, dataID)
}

// Get mocks base method.
func (m *MockDataRepository) Get(ctx context.Context, userID, dataID string) (*models.Data, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, userID, dataID)
	ret0, _ := ret[0].(*models.Data)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockDataRepositoryMockRecorder) Get(ctx, userID, dataID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockDataRepository)(nil).Get), ctx, userID, dataID)
}

// GetSince mocks base method.
func (m *MockDataRepository) GetSince(ctx context.Context, userID string, since time.Time) ([]*models.Data, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSince", ctx, userID, since)
	ret0, _ := ret[0].([]*models.Data)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSince indicates an expected call of GetSince.
func (mr *MockDataRepositoryMockRecorder) GetSince(ctx, userID, since any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSince", reflect.TypeOf((*MockDataRepository)(nil).GetSince), ctx, userID, since)
}

// List mocks base method.
func (m *MockDataRepository) List(ctx context.Context, userID string, dataType models.DataType) ([]*models.Data, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, userID, dataType)
	ret0, _ := ret[0].([]*models.Data)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockDataRepositoryMockRecorder) List(ctx, userID, dataType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockDataRepository)(nil).List), ctx, userID, dataType)
}

// Save mocks base method.
func (m *MockDataRepository) Save(ctx context.Context, userID string, data *models.Data) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, userID, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockDataRepositoryMockRecorder) Save(ctx, userID, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockDataRepository)(nil).Save), ctx, userID, data)
}
